# Generated by Django 3.1.5 on 2021-04-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='users/%Y/%m/%d')),
                ('sex', models.CharField(blank=True, choices=[('', 'Choose....'), ('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('educational_background', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('', 'Choose....'), ('Married', 'Married'), ('Single', 'Single')], max_length=200, null=True)),
                ('home_address', models.CharField(blank=True, default='e.g No 2 Aba Rd, Uyo, Akwa Ibom State', max_length=200, null=True)),
                ('phone_no', models.PositiveIntegerField(blank=True, default='08053453251', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
