# Generated by Django 3.1.5 on 2021-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
