# Generated by Django 3.1.5 on 2021-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.jpeg', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
