# Generated by Django 3.1.5 on 2021-05-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210506_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
