# Generated by Django 3.1.5 on 2021-04-07 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homapp', '0003_auto_20210402_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
