# Generated by Django 3.1.5 on 2021-04-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homapp', '0005_auto_20210407_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='Add some description'),
        ),
    ]
