# Generated by Django 3.1.5 on 2021-04-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homapp', '0008_auto_20210409_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance', to='homapp.financecategory'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wears', to='homapp.wearcategory'),
        ),
    ]
