# Generated by Django 3.1.5 on 2021-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homapp', '0009_auto_20210410_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='photo',
            field=models.ImageField(blank=True, null='', upload_to='finance/%Y/%m/%d'),
        ),
    ]
