# Generated by Django 3.1.5 on 2021-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homapp', '0010_finance_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wear',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
